[server]
listen = "127.0.0.1:3000"
docroot = "static"
concurrency_limit = 10
loglevel = "info"

[database]
materialized_view_ttl = 1
max_connections = 10

[ldap]
#url = "ldaps://axingc.central.inditex.grp:3269"
url = "ldaps://localhost:3269"
domain = "central.inditex.grp"
search = "dc=central,dc=inditex,dc=grp"
member_of = "CN=foremanreports,OU=Produccion,OU=Programas,OU=Grupos,OU=Arteixo,OU=Sedes,DC=central,DC=inditex,DC=grp"


