[server]
listen = "127.0.0.1:3100"
concurrency_limit = 10

[database]
url = "postgres://foreman_reports:94gzdEDS3f34fsd%23~@127.0.0.1:5432/foreman_reports"
materialized_view_ttl = 1
max_connections = 10

[ldap]
url = "ldaps://axingc.central.inditex.grp:3269"
domain = "central.inditex.grp"
search = "dc=central,dc=inditex,dc=grp"
member_of = "CN=foremanreports,OU=Produccion,OU=Programas,OU=Grupos,OU=Arteixo,OU=Sedes,DC=central,DC=inditex,DC=grp"
